New norg2 unit
navikt/crm-nks-base-components pull request #115
Opened 2023-08-15 06:32 UTC by mamikals

2023-08-18 10:02 UTC, EirikFladby requested changes

2023-08-18 10:02 UTC, EirikFladby commented on force-app/main/default/lwc/nksNavUnitSingle/nksNavUnitSingle.js
>  export default class NksNavUnitSingle extends LightningElement {
Klarer ikke se hvor denne brukes?

2023-08-28 06:36 UTC, mamikals commented on force-app/main/default/lwc/nksNavUnitSingle/nksNavUnitSingle.js
>  export default class NksNavUnitSingle extends LightningElement {
Hvilken? Hva er det du tenker på?

2023-08-28 06:37 UTC, mamikals commented on force-app/main/default/classes/NKS_NavUnitSingleControllerTest.cls
> +    @IsTest
Sure, det er nok ikke dumt

2023-08-28 06:37 UTC, mamikals commented on force-app/main/default/classes/NKS_NorgNavUnitService.cls
> +                resp.errorMessage = 'Kunne ikke finne enhets insformasjon. Referanse til feil: ' + errorRef;
Fair, jeg kopierte jo bare koden fra V1 av APIet, men jeg burde lest over etter skrivefeil hehe, har fikset begge metodene

2023-08-28 06:37 UTC, mamikals commented on force-app/main/default/classes/NKS_NorgNavUnitService.cls
> +            if (true == String.isNotBlank(bodyString)) {
Enig, det var litt rart, jeg fikset begge metodene her og

2023-08-28 09:25 UTC, EirikFladby commented on force-app/main/default/lwc/nksNavUnitSingle/nksNavUnitSingle.js
>  export default class NksNavUnitSingle extends LightningElement {
Nvm :D

2023-08-28 10:53 UTC, EirikFladby approved these changes

2023-08-28 10:53 UTC, EirikFladby commented on force-app/main/default/classes/NKS_NavUnitSingleControllerTest.cls
> +}
Fjern denne :D

2023-08-28 10:53 UTC, EirikFladby commented on force-app/main/default/classes/NKS_NorgNavUnitService.cls
Ser at det er flere tilfeller av "true == String.isNotBlank(bodyString)". Gidder du cleane de opp og? Linje 129 og 276

2023-08-28 11:07 UTC, mamikals commented on force-app/main/default/classes/NKS_NavUnitSingleControllerTest.cls
> +}
Rude, det va du som ba mæ om æ legge den inn

2023-08-28 11:11 UTC, mamikals commented on force-app/main/default/classes/NKS_NavUnitSingleControllerTest.cls
> +}
Ahhh nvm æ ser den lmao. Yeah sry min feil, gadd ikke å lage en scratch for å validate endringen mot hehe

2023-08-31 10:56 UTC, mamikals commented
Se #118

2023-08-31 10:56 UTC, closed without merging