added flow button container cmp
navikt/crm-nks-base-components pull request #167
Opened 2024-05-04 19:50 UTC by saramoh2309

2024-05-14 09:18 UTC, JanRobertNav requested changes

2024-05-14 09:18 UTC, JanRobertNav commented on force-app/main/default/lwc/nksButtonContainerBottom/nksButtonContainerBottom.html
> +            </template>
Flytte logikk til JavaScript og korte ned til en lightningflow. Den skal åpne den andre flowen direkte.

2024-05-14 09:18 UTC, JanRobertNav commented on force-app/main/default/lwc/nksButtonContainerBottom/nksButtonContainerBottom.js
> +        publishToAmplitude(this.channelName, { type: `${event.target.label} pressed` });
Flytte til handleStatusChange når finnished.

2024-05-14 09:18 UTC, JanRobertNav commented on force-app/main/default/lwc/nksButtonContainerTop/nksButtonContainerTop.css
> +    display: grid;
Se om denne kan sløyfes

2024-05-14 09:18 UTC, JanRobertNav commented on force-app/main/default/lwc/nksButtonContainerTop/nksButtonContainerTop.css
> +.button {
Endre klassenavn til f.eks "full-width-button"

2024-05-14 09:18 UTC, JanRobertNav commented on force-app/main/default/lwc/nksButtonContainerTop/nksButtonContainerTop.html
> +            <template if:true={showFlow}>
lwc:if

2024-05-14 09:18 UTC, JanRobertNav commented on force-app/main/default/lwc/nksButtonContainerTop/nksButtonContainerTop.js
> +            publishToAmplitude(this.channelName, { type: event.target.label + ' pressed' });
Flytte til handleStatusChange når finnished.

2024-05-22 13:31 UTC, mamikals commented on force-app/main/default/lwc/nksButtonContainerTop/nksButtonContainerTop.css
> +    display: grid;
Det kunne den ikke 😄

2024-05-23 13:12 UTC, JanRobertNav approved these changes

2024-05-23 13:27 UTC, merged