Nks 1760
navikt/crm-nks-base-components pull request #187
Opened 2024-06-18 11:16 UTC by saramoh2309

2024-06-24 13:57 UTC, EirikFladby requested changes

2024-06-24 13:57 UTC, EirikFladby commented on force-app/main/default/classes/NKS_ButtonContainerController_Test.cls
> +        System.assertEquals('Arbeid', result, 'The name should match the inserted Common_Code__c record');
Bruk Assert

2024-06-24 13:57 UTC, EirikFladby commented on force-app/main/default/lwc/nksButtonContainerTop/nksButtonContainerTop.js
> +    publishMessag(outputVariables) {
```suggestion
    publishMessage(outputVariables) {
```

2024-06-24 13:57 UTC, EirikFladby commented on force-app/main/default/lwc/nksButtonContainerTop/nksButtonContainerTop.js
> +            this.publishMessag(outputVariables);
```suggestion
            this.publishMessage(outputVariables);
```

2024-06-24 13:57 UTC, EirikFladby commented on force-app/main/default/lwc/nksButtonContainerUtils/nksButtonContainerUtils.js
> +                : 'Henvendelsen er journalført';
Man må vel alltid dele med bruker når man journalfører på samtalereferat? Er det noen tilfeller hvor henvendelsen bare journalføres, men ikke deles? Det går vel ikke lenger?

2024-06-24 13:57 UTC, EirikFladby commented on force-app/main/default/lwc/nksButtonContainerUtils/nksButtonContainerUtils.js
> +        const selectedThemeId = getOutputVariableValue(outputVariables, 'Selected_Theme_SF_Id');
Er det en grunn til at vi sender tema-id istedenfor temanavn her? Kan potensielt slippe en query.

2024-06-24 13:57 UTC, EirikFladby commented on force-app/main/default/lwc/nksNotificationBox/nksNotificationBox.js
> +    }
Brukes ikke?

2024-06-25 10:08 UTC, EirikFladby requested changes

2024-06-25 10:08 UTC, EirikFladby commented on force-app/main/default/lwc/nksButtonContainerBottom/nksButtonContainerBottom.js
> +    }
Kan vi ikke heller subscribe i connected?

2024-06-25 10:08 UTC, EirikFladby commented on force-app/main/default/lwc/nksNotificationBox/nksNotificationBox.js
> +    }
Brukes ikke?

2024-06-26 10:10 UTC, saramoh2309 commented on force-app/main/default/lwc/nksButtonContainerUtils/nksButtonContainerUtils.js
> +                : 'Henvendelsen er journalført';
Ja, det er tilfeller bruker trenger bare journalføre en eksisterende henvendelse

2024-06-26 10:13 UTC, saramoh2309 commented on force-app/main/default/lwc/nksButtonContainerUtils/nksButtonContainerUtils.js
> +        const selectedThemeId = getOutputVariableValue(outputVariables, 'Selected_Theme_SF_Id');
I komponentene for journalføring (personCaseOverview) og oppretting av oppgave (themeCategorization) finnes bare tema-id som output. Mulig vi kan legge til tema-navn som output i disse komponentene, men da må vi kjøre query igjen?

2024-06-26 10:17 UTC, saramoh2309 commented on force-app/main/default/lwc/nksButtonContainerBottom/nksButtonContainerBottom.js
> +                );
showNotification variable er brukt for chat der vi bruker denne komponenten under chat-vindu som en separat komponent. Custom event brukes for conversation note; hvis jeg skjønt spørsmålet riktig?

2024-06-27 14:42 UTC, EirikFladby commented on force-app/main/default/lwc/nksButtonContainerUtils/nksButtonContainerUtils.js
> +        const selectedThemeId = getOutputVariableValue(outputVariables, 'Selected_Theme_SF_Id');
Kan sende navn, men blir en del endringer ser jeg.

2024-06-27 14:47 UTC, EirikFladby commented on force-app/main/default/lwc/nksButtonContainerBottom/nksButtonContainerBottom.js
> +                );
Ok, så showNotifications er kun relevant for chat? Det hadde vært nice med en kommentar på det i koden. Det er ikke veldig intuitivt at det er det som er tilfellet😄

2024-06-28 11:33 UTC, EirikFladby approved these changes

2024-06-28 11:49 UTC, merged